# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_kaggle_dataset": "00_setup.ipynb",
         "pathFromCompetition": "00_setup.ipynb",
         "confirm": "00_setup.ipynb",
         "download_and_log": "00_setup.ipynb",
         "setup": "00_setup.ipynb"}

modules = ["data.py"]

doc_url = "https://fredguth.github.io/nfwk/"

git_url = "https://github.com/fredguth/nbdev_wandb_kaggle/tree/master/"

def custom_doc_links(name): return None
